#!/bin/sh -e

##########################################################################
#   Script description:
#       Upload samples to AWS instance
#       
#   History:
#   Date        Name        Modification
#   2020-07-27  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 sample-group (e.g. whi, bjm)\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
sample_group=$1

cat << EOM

This will update scripts on all instances.

This should not be done if AWS jobs are running.

EOM
read -p "Are you sure? (yes/[no]) " sure
if [ 0$sure != 0yes ]; then
    exit
fi

cd ~/Data/TOPMed/Jobs/Haplohseq-analysis/SRA
key='-i ~/.ssh/aws-us-east.pem'
sample_group=$1

for host in $(cat aws-ips); do
    ssh -x -t $key ec2-user@$host 'cd Haplohseq-analysis && git pull -r'
done
