#!/bin/sh -e

proper_cmd=Local-scripts/bjm-sample-list
if [ $0 != $proper_cmd ]; then
    printf "$0 must be run as $proper_cmd.\n"
    exit 1
fi
xzcat TOPMed_SraRunTable_20200729.txt.xz | \
    awk '($1 == "BioMe" || $1 == "JHS" || $1 == "MESA") && ($2 != "phs000920" && $2 != "phs000921") { print $3,$4,$1 }' \
    > Sample-lists/bjm-samples.unchecked
rm -f Sample-lists/bjm-samples.txt
while read line; do
    sample=$(echo $line | awk '{ print $1 }')
    if [ -e ../Split-vcfs/Combined/combined.$sample.vcf.xz ]; then
	echo "$line" >> Sample-lists/bjm-samples.txt
    else
	printf "Missing VCF for $sample\n"
    fi
done < Sample-lists/bjm-samples.unchecked
diff Sample-lists/bjm-samples.unchecked Sample-lists/bjm-samples.txt || true
wc -l Sample-lists/bjm-samples.unchecked Sample-lists/bjm-samples.txt
printf "Now run split-sample-list to evenly divide the list for ad2vcf.\n"
