#!/bin/sh -e

##########################################################################
#   Script description:
#       Show progress of AWS jobs
#       
#   History:
#   Date        Name        Modification
#   2020-09-13  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 sample-group (e.g. whi, bjm)\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
sample_group=$1

cd ~/Data/TOPMed/Jobs/Haplohseq-analysis/SRA
job_count=$(AWS-scripts/job-count)

# ~/scripts/aws-run aws-ips 'ls Haplo*/SRA/VCF*/*.xz | wc -l'
~/scripts/aws-run -c "ls Haplohseq-analysis/SRA/VCFs-$sample_group-*/*.xz | wc -l && ls Haplohseq-analysis/SRA/VCFs-$sample_group-*/Done/*.xz | wc -l"
~/scripts/aws-run -c "cd Haplo*/SRA && AWS-scripts/run-times $job_count VCFs-$sample_group-*/Logs"
# ~/scripts/aws-run aws-ips 'xzcat Haplo*/SRA/VCF*/Done/*.xz | head -2'
