#!/bin/sh -e

##########################################################################
#   Script description:
#       Show progress of AWS jobs
#       
#   History:
#   Date        Name        Modification
#   2020-09-13  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 prefix\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
prefix=$1

cd ~/Data/TOPMed/Jobs/Haplohseq-analysis/SRA
job_count=$(AWS-scripts/job-count)

# ~/scripts/aws-run whi-aws-ips 'ls Haplo*/SRA/VCF*/*.xz | wc -l'
~/scripts/aws-run whi-aws-ips "ls Haplohseq-analysis/SRA/VCFs-$prefix-*/Done/*.xz | wc -l"
~/scripts/aws-run whi-aws-ips "cd Haplo*/SRA && AWS-scripts/run-times $job_count VCFs-$prefix-*/Logs"
# ~/scripts/aws-run whi-aws-ips 'xzcat Haplo*/SRA/VCF*/Done/*.xz | head -2'
