#!/bin/sh -e

#~/scripts/aws-run whi-aws-ips 'ls Haplo*/SRA/VCF*/*.xz | wc -l'
~/scripts/aws-run whi-aws-ips 'ls Haplo*/SRA/VCF*/Done/*.xz | wc -l'
#~/scripts/aws-run whi-aws-ips 'xzcat Haplo*/SRA/VCF*/Done/*.xz | head -2'
