#!/bin/sh -e

##########################################################################
#   Script description:
#       Count VCFs pre and post ad2vcf
#       
#   History:
#   Date        Name        Modification
#   2020-09-20  Jason Bacon Begin
##########################################################################

##########################################################################
#   Main
##########################################################################

cd ~/Data/TOPMed/Jobs/Haplohseq-analysis/SRA
printf "%-22s %8s %8s %8s\n" "Group" "Raw" "MAPQ 0" "MAPQ 10"
for sample_group in array whi bjm group3 group4; do
    for vcf_dir in VCFs-$sample_group-*; do
	raw=$(find $vcf_dir -maxdepth 1 -name '*.vcf.xz' | wc -l)
	mapq0=$(find $vcf_dir/Done-MAPQ-0/ -maxdepth 1 -name '*.vcf.xz' | wc -l)
	mapq10=$(find $vcf_dir/Done-MAPQ-10/ -maxdepth 1 -name '*.vcf.xz' 2> /dev/null | wc -l)
	printf "%-22s %8u %8u %8u\n" $vcf_dir $raw $mapq0 $mapq10
    done
done
printf "Total completed: $(find VCFs-*/Done* -maxdepth 1 -name '*.vcf.xz' | wc -l)\n"
