#!/bin/sh -e

run_table=TOPMed_SraRunTable_20200729.txt.xz
cd ~/Data/TOPMed/Jobs/Haplohseq-analysis/SRA
printf "Samples listed in $run_table: 18504\n"
xzcat $run_table | \
    awk '($1 == "SAPPHIRE_asthma" || $1 == "REDS-III_Brazil" || $1 == "walk_PHaSST" || $1 == "MLOF" || $1 == "GALAI" || $1 == "OMG_SCD" || $1 == "CARDIA" || $1 == "GGAF") && $2 != "phs000920" && $2 != "phs000921" { print $3,$4,$1 }' \
    > Sample-lists/group6-samples.unchecked
rm -f Sample-lists/group6-samples.txt
xzcat TOPMed_SraRunTable_20200729.txt.xz > TOPMed_SraRunTable_20200729.txt
while read line; do
    sample=$(echo $line | awk '{ print $1 }')
    if [ -e ../Split-vcfs/Combined/combined.$sample.vcf.xz ]; then
	echo "$line" >> Sample-lists/group6-samples.txt
    else
	printf "Missing VCF for "
	awk -v sample=$sample '$3 == sample { print $1, $2, $3 }' \
	    TOPMed_SraRunTable_20200729.txt
    fi
done < Sample-lists/group6-samples.unchecked
diff Sample-lists/group6-samples.unchecked Sample-lists/group6-samples.txt || true
wc -l Sample-lists/group6-samples.unchecked Sample-lists/group6-samples.txt
