#!/bin/sh -e

run_table=TOPMed_SraRunTable_20200729.txt.xz
cd ~/Data/TOPMed/Jobs/Haplohseq-analysis/SRA
printf "Samples listed in $run_table: 16200\n"
xzcat $run_table | \
    awk '($1 == "GENOA" || $1 == "GOLDN" || $1 == "CHS" || $1 == "THRV" || $1 == "HCHS_SOL" || $1 == "Mayo_VTE" || $1 == "DHS" || $1 == "SARP" || $1 == "PharmHU") && $2 != "phs000920" && $2 != "phs000921" { print $3,$4,$1 }' \
    > Sample-lists/group5-samples.unchecked
rm -f Sample-lists/group5-samples.txt
xzcat TOPMed_SraRunTable_20200729.txt.xz > TOPMed_SraRunTable_20200729.txt
while read line; do
    sample=$(echo $line | awk '{ print $1 }')
    if [ -e ../Split-vcfs/Combined/combined.$sample.vcf.xz ]; then
	echo "$line" >> Sample-lists/group5-samples.txt
    else
	printf "Missing VCF for "
	awk -v sample=$sample '$3 == sample { print $1, $2, $3 }' \
	    TOPMed_SraRunTable_20200729.txt
    fi
done < Sample-lists/group5-samples.unchecked
diff Sample-lists/group5-samples.unchecked Sample-lists/group5-samples.txt || true
wc -l Sample-lists/group5-samples.unchecked Sample-lists/group5-samples.txt
