#!/bin/sh -e

##########################################################################
#   Script description:
#       Pre-populate GCP instance with hts-ref cache
#       
#   History:
#   Date        Name        Modification
#   2020-07-27  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 instance-name\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
instance=$1

gcloud compute scp --compress Save/pkgsrc-RHEL7-gcc-8.0-usr-pkg.tgz \
    ${instance}:
