#!/bin/sh -e

##########################################################################
#   Script description:
#       Upload samples to AWS instance
#       
#   History:
#   Date        Name        Modification
#   2020-07-27  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 prefix\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
prefix=$1

cd ~/Data/TOPMed/Jobs/Haplohseq-analysis/SRA
key='-i ~/.ssh/aws-us-east.pem'
dest_dir=Haplohseq-analysis/SRA

c=0
for host in $(cat $prefix-aws-ips); do
    sample_dir=$(printf "VCFs-$prefix-samples-%02d" $c)
    sample_file=$(printf "Sample-lists/$prefix-samples-%02d" $c)
    c=$((c + 1))
    echo $sample_dir
    mkdir $sample_dir
    for sample in $(awk '{ print $1 }' $sample_file); do
	if ! ln ../Split-vcfs/Combined/combined.$sample.vcf.xz $sample_dir; then
	    printf "$sample\n" >> $sample_dir/missing-samples.txt
	fi
    done
    find $sample_dir -name '*.xz' | wc -l
    ssh $key ec2-user@$host mkdir -p $dest_dir
    rsync -av --delete --progress -e "ssh $key" $sample_dir ec2-user@$host:$dest_dir
done
