#!/bin/sh -e

##########################################################################
#   Script description:
#       Split sample list into N components
#       
#   History:
#   Date        Name        Modification
#   2020-09-09  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 filename chunks\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi
master_list=$1
chunks=$2

total_lines=$(cat $master_list | wc -l)
lines=$(($total_lines / $chunks + 1))
split -d -l $lines $master_list ${master_list%.*}-
