#!/bin/sh -e

##########################################################################
#   Script description:
#       Upload samples to AWS instance
#       
#   History:
#   Date        Name        Modification
#   2020-07-27  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 sample-group (e.g. whi, bjm) [extra-rsync-args]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 1 ]; then
    usage
fi
sample_group=$1
shift

cat << EOM

This will delete files from AWS that are not on $(hostname -s).

This should not be done if AWS jobs are using the files to be uploaded.

EOM
read -p "Are you sure? (yes/[no]) " sure
if [ 0$sure != 0yes ]; then
    exit
fi

cd ~/Data/TOPMed/Jobs/Haplohseq-analysis/SRA
key='-i ~/.ssh/aws-us-east.pem'
dest_dir=Haplohseq-analysis/SRA
mkdir -p Transfer-logs

c=0
for host in $(cat aws-ips); do
    sample_dir=$(printf "VCFs-$sample_group-samples-%02d" $c)
    sample_file=$(printf "Sample-lists/$sample_group-samples-%02d" $c)
    echo $sample_dir
    mkdir -p $sample_dir
    rm -f $sample_dir/missing-samples.txt
    for sample in $(awk '{ print $1 }' $sample_file); do
	if ! ln -f ../Split-vcfs/Combined/combined.$sample.vcf.xz $sample_dir; then
	    study=$(awk -v sample=$sample '$1 == sample { print $3 }' $sample_file)
	    printf "$sample $study\n" >> $sample_dir/missing-samples.txt
	fi
    done
    find $sample_dir -name '*.xz' | wc -l
    ssh -x $key ec2-user@$host mkdir -p $dest_dir
    nohup rsync -av --delete -e "ssh $key" $sample_dir ec2-user@$host:$dest_dir \
	> Transfer-logs/$sample_dir-upload.log 2>&1 &
    c=$((c + 1))
done
