#!/bin/sh -e

cd ~/Data/TOPMed/Jobs/Haplohseq-analysis/SRA
rm -f corrupt-vcfs
for file in VCFs-*/Done/*.xz; do
    printf "$file "
    if ./AWS-scripts/validate-vcf $file; then
	printf "OK\n"
    else
	printf "Corrupt\n"
	printf "$file\n" >> corrupt-vcfs
    fi
done
