#!/bin/sh -e

##########################################################################
#   Script description:
#       Confirm that the position of the last call matches in input and
#       output files.  This is also done by ad2vcf.sh on group4 and later.
#       
#   History:
#   Date        Name        Modification
#   2020-09-25  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 directory\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
dir=$1

cd $dir
for file in *.vcf.xz; do
    printf "===\n"
    xzcat $file | tail -n 1 | awk '{ print $2 }'
    xzcat Done/${file%.vcf.xz}-ad.vcf.xz | tail -n 1 | awk '{ print $2 }'
done
