#!/bin/sh -e

##########################################################################
#   Script description:
#       Confirm that the position of the last call matches in input and
#       output files.  This is also done by ad2vcf.sh on group4 and later.
#       
#   History:
#   Date        Name        Modification
#   2020-09-25  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

cd ~/Data/TOPMed/Jobs/Haplohseq-analysis/SRA/
for dir in VCFs-*-[0-9][0-9]; do
    for file in $dir/*.vcf.xz; do
	printf "$file: "
	input_pos=$(xzcat $file | tail -n 1 | awk '{ print $2 }')
	base=$(basename $file)
	output_file=$dir/Done/${base%.vcf.xz}-ad.vcf.xz
	output_pos=$(xzcat $output_file | tail -n 1 | awk '{ print $2 }')
	printf "%10s %10s " $input_pos $output_pos
	if [ $input_pos != $output_pos ]; then
	    printf "Mismatch!\n"
	    printf "$output_file is missing calls\n" >> corrupt-VCFs.txt
	else
	    printf "OK\n"
	fi
    done
done
