#!/bin/sh -e

proper_cmd=Local-scripts/whi-sample-list
if [ $0 != $proper_cmd ]; then
    printf "$0 must be run as $proper_cmd.\n"
    exit 1
fi
xzcat TOPMed_SraRunTable_20200729.txt.xz | \
    awk '$1 == "WHI" && $2 != "phs000920" && $2 != "phs000921" { print $3,$4 }' \
    > Sample-lists/whi-samples.txt
printf "Now run split-sample-list to evenly divide the list for ad2vcf.\n"
