#!/bin/sh -e

corrupt_vcfs="corrupt-vcfs.txt"

for file in SRA/Results-available-*/Done/combined.*-ad.vcf.xz; do
    last_line=$(xzcat $file | tail -n 1)
    cols=$(echo $last_line | awk '{ print NF }')
    if [ $cols != 10 ]; then
	printf "\nLast line in $file has $cols columns, should be 10.\n" \
	    >> $corrupt_vcfs
    else
	sample=$(echo $last_line | awk '{ print $10 }')
	ad=$(echo $sample | awk -F : '{ print $2 }')
	ref=$(echo $ad | awk -F , '{ print $1 }')
	alt=$(echo $ad | awk -F , '{ print $2 }')
	dp=$(echo $sample | awk -F : '{ print $3 }')
	# printf "$sample $ref $alt $dp\n"
	if [ $((ref + alt)) != $dp ]; then
	    printf "\nref + alt != dp\n" >> $corrupt_vcfs
	else
	    printf "."
	fi
    fi
done
