#!/bin/sh -e

##########################################################################
#   Script description:
#       Generate variant site lists for a given minimum allele frequency
#       
#   History:
#   Date        Name        Modification
#   2021-02-11  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 MAF\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
maf=$1
sbatch 3c-find-maf-sites.sbatch $maf
