#!/bin/sh -e

##########################################################################
#   Script description:
#       Filter sites for minimum allele frew (MAF) and minimum distance
#       from each other
#       
#   History:
#   Date        Name        Modification
#   2020-09-13  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 sample-group (e.g. whi, bjm)\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
sample_group=$1

maf=0.01            # Minimum allele frequency
separation=1000     # Min distance between events
vcf_dir=AD-VCFs-$sample_group

sample_count=$(find $vcf_dir -depth 1 -name '*-ad.vcf.xz' | wc -l)
sample_count=$(printf "%d" $sample_count)   # Strip leading space
printf "Samples: $sample_count\n"

mkdir -p AD-VCFs-$sample_group/MAF-$maf-${separation}nt
sbatch --array=1-$sample_count%50 \
    3d-filter-sites.sbatch $sample_group $maf $separation
