#!/bin/sh -e

##########################################################################
#   Script description:
#       Filter sites for minimum allele frew (MAF) and minimum distance
#       from each other
#       
#   History:
#   Date        Name        Modification
#   2020-09-13  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 sample-group min-allele-frequency min-separation\n"
    printf "Example: $0 whi 0.05 1000\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 3 ]; then
    usage
fi
sample_group=$1
maf=$2              # Minimum allele frequency
separation=$3       # Min distance between events

# Filter using database of genomic variants
dgv_gff=DGV.GS.hg38.gff3
if [ ! -e $dgv_gff ]; then
    curl -O http://dgv.tcag.ca/dgv/docs/$dgv_gff
fi

vcf_dir=AD-VCFs-$sample_group
vcf_list=$vcf_dir/VCF-list.txt

ls $vcf_dir | grep '.*-ad\.vcf\.xz' > $vcf_list
sample_count=$(cat $vcf_list | wc -l)
sample_count=$(printf "%d" $sample_count)   # Strip leading space
printf "Samples: $sample_count\n"

mkdir -p $vcf_dir/MAF-$maf-${separation}nt
sbatch --array=1-$sample_count%50 \
    3d-filter-sites.sbatch $sample_group $maf $separation
