#!/bin/sh -e

##########################################################################
#   Script description:
#       Split germline structural event BCFs, outputting only specified
#       samples and only those containing an ALT allele (1 in either copy)
#       
#   History:
#   Date        Name        Modification
#   2021-02-20  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi
# sample_list=$1

export PATH=~/Barracuda/TOPMed/local/bin:$PATH
which vcf-split
total_samples=$(bcftools view 79852-germline-structural-variants/sv.freeze1.chr9.gt.only.bcf | grep -m 1 '^#CHROM' | awk '{ print NF-9 }')
printf "Total samples = $total_samples\n"

cd 79852-germline-structural-variants
output_dir=Split-vcfs
mkdir -p $output_dir
cd $output_dir

for first_col in $(seq 1 10000 $total_samples); do
    last_col=$(( first_col + 9999 ))
    test $last_col -gt $total_samples && last_col=$total_samples
    printf "Processing columns $first_col to $last_col...\n"
    for file in sv.freeze1.*.gt.only.bcf; do
	chr=$(echo $file | cut -d . -f 3)
	printf "$file $chr\n"
	mkdir -p $chr
	bcftools view $file \
	    | vcf-split --alt-only --output-fields chrom,id,pos,format \
		$output_dir/$chr/$chr. $first_col $last_col
    done
done
