#!/bin/sh -e

##########################################################################
#   Script description:
#       Concatenate germline structural event BCFs, only those containing
#       an ALT allele ('1' in either copy)
#       
#   History:
#   Date        Name        Modification
#   2021-02-20  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi
sample_list=$1

cd 79852-germline-structural-variants/Split-vcfs
done=0
samples=$(bcftools view ../sv.freeze1.chr9.gt.only.bcf | grep -m 1 '^#CHROM' | cut -f 10-)
printf "Concatenating %s samples...\n" $(echo $samples | wc -w)
for sample in $samples; do
    files=""
    for chr in $(seq 1 22); do
	files="$files chr$chr/chr$chr.$sample.vcf"
	chr=$((chr + 1))
    done
    combined=combined.$sample.vcf.xz
    printf "===\n%u\nConcatenating $files to $combined...\n" $done
    done=$((done + 1))
    # Add only 1 copy of header
    (head chr1/chr1.$sample.vcf | grep '^#' && grep --no-filename -v '^#' $files) | xz > $combined
done
