#!/bin/sh -e

##########################################################################
#   Script description:
#       Concatenate germline structural event BCFs, outputting only specified
#       samples and only those containing an ALT allele (1 in either copy)
#       
#   History:
#   Date        Name        Modification
#   2021-02-20  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 sample-list\n"
    printf "sample-list is a simple text file with one sample per line.\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
sample_list=$1

dir=Split-vcfs-$(basename $sample_list)
cd 79852-germline-structural-variants/$dir
done=0
for sample in $(cat ../../$sample_list); do
    chr=1
    files=""
    while [ $chr -le 22 ]; do
	files="$files chr$chr.$sample.vcf"
	chr=$((chr + 1))
    done
    combined=combined.$sample.vcf.xz
    printf "===\n%u\nConcatenating $files to $combined...\n" $done
    done=$((done + 1))
    # Add only 1 copy of header
    (head chr1.$sample.vcf | grep '^#' && grep --no-filename -v '^#' $files) | xz > $combined
done
