#!/bin/sh -e

##########################################################################
#   Script description:
#       Run haplohseq on all .vcf.xz files in a directory
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2020-09-13  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 dir [sbatch flags]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 1 ]; then
    usage
fi
vcf_dir=$1
shift

sample_count=$(find $vcf_dir -depth 1 -name '*.vcf.xz' | wc -l)
sample_count=$(printf "%d" $sample_count)   # Strip leading space

set -x
sbatch --array=1-$sample_count%50 "$@" 3e-haplohseq.sbatch $vcf_dir
