#!/bin/sh -e

##########################################################################
#   Script description:
#       Run haplohseq on all .vcf.xz files in a directory
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2020-09-13  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 ad-vcf-dir [sbatch flags]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 1 ]; then
    usage
fi
vcf_dir=$1
shift

ls $vcf_dir | grep '.*\.vcf\.xz' > $vcf_dir/VCF-list.txt
sample_count=$(cat $vcf_dir/VCF-list.txt | wc -l)
sample_count=$(printf "%d" $sample_count)   # Strip leading space

set -x
sbatch --array=1-$sample_count%100 "$@" 3e-haplohseq.sbatch $vcf_dir
