#!/bin/sh -e

##########################################################################
#   Script description:
#       Convert structural event BCFs to bed format for bedtools subtract
#       
#   History:
#   Date        Name        Modification
#   2021-02-20  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi
cd 79852-germline-structural-variants/Split-vcfs
pwd
for file in combined*.vcf.xz; do
    bed=${file%.vcf.xz}.bed
    printf "$file -> $bed...\n"
    xzcat $file | grep -v '^#' | mawk -f ../../extract-range.awk > ${bed}
done
