#!/bin/sh -e

##########################################################################
#   Script description:
#       Generate a list of the first 5k samples in TOPMed
#       
#   History:
#   Date        Name        Modification
#   2021-03-03  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 MAF\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
maf=$1

# Take samples from WHI
cd AD-VCFs-whi-MAPQ-0/MAF-$maf
pwd
find . -mindepth 1 -maxdepth 1 -name 'combined.*.xz' \
    | awk -F '[.-]' '{ print $3 }' | head -n 5000 > 5k-samples.txt
