#!/bin/sh -e

##########################################################################
#   Script description:
#       Uncompress VCF files in preparation for running ad-matrix
#       There are too many files to run an xzcat filter on all at once
#       
#   History:
#   Date        Name        Modification
#   2021-03-03  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 sample-list\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
sample_list=$1

cd AD-VCFs-whi-MAPQ-0
mkdir -p Uncompressed
for sample in $(cat ../$sample_list); do
    echo $sample
    xzcat combined.$sample-ad.vcf.xz > Uncompressed/combined.$sample-ad.vcf
done
