#!/bin/sh -e

##########################################################################
#   Script description:
#       Uncompress VCF files in preparation for running ad-matrix
#       There are too many files to run an xzcat filter on all at once
#       
#   History:
#   Date        Name        Modification
#   2021-03-03  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 sample-list MAF\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi
sample_list=$1
maf=$2

dir=AD-VCFs-whi-MAPQ-0/MAF-$maf
mkdir -p $dir/Uncompressed

# Strip spaces inserted by wc
count=$(cat $dir/$sample_list | wc -l | tr -d ' ')

# This will be I/O intensive, so just run on a few samples at a time on the
# local disk
printf "Processing $count samples in $dir...\n"
sbatch --array=1-${count}%4 --nodelist=barracuda 4c-uncompress-samples.sbatch \
    $sample_list $maf
