#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2020-09-24  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 hash\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
hash=$1

nwid=$(awk -v hash=$hash '$2 == hash { print $1 }' de-ident-mappings.txt)
printf "$nwid\n"
xzcat AD-VCFs-whi/combined.$nwid-ad.vcf.xz | tail -n 1
printf "Scanning logs...\n"
set +e
logs=$(find SLURM-outputs -name haplohseq\*.out | xargs fgrep -l $nwid)
echo $logs
for log in $logs; do
    cat $log
    cat ${log%.out}.err
done
