#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2021-04-28  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 sample-group\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
sample_group=$1

./3h-haplohseq AD-VCFs-$sample_group-MAPQ-0/MAF-0.01-1000nt-sv 0.01 30 10 y
