#!/bin/sh -e

##########################################################################
#   Script description:
#       Pre-populate GCP instance with hts-ref cache
#       
#   History:
#   Date        Name        Modification
#   2020-07-27  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 instance-name\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
instance=$1

gcloud compute ssh $instance --command="mkdir -p .cache"
gcloud compute scp --compress --recurse ~/.cache/hts-ref ${instance}:.cache
