#!/bin/sh

##########################################################################
#   Script description:
#       Remove filter outputs for samples without structural variants
#       
#   History:
#   Date        Name        Modification
#   2021-04-29  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 sample-group\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
group=$1

for sample in $(find SLURM-outputs-$group -name filter-sites-50052\*.err | 
    xargs cat | awk -F "[ .]" '{ print $9 }'); do
    echo $sample
    rm -i AD-VCFs-whi-MAPQ-0/MAF-0.01-1000nt-sv/*$sample*
done
