#!/bin/sh -e

nohup rsync -av --size-only \
    --exclude '*.vcf' --exclude SLURM-compress-outputs \
    peregrine.hpc.uwm.edu:Data/TOPMed/Jobs/Haplohseq-analysis/Split-vcfs . \
    > sync.log 2>&1 &
