#!/bin/sh -e

usage()
{
    printf "Usage: $0 dir\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

# AD-VCFs-whi/MAF-0.01-1000nt
cd $1
while true; do
    ls | grep 'combined.*\.vcf\.xz' | wc -l
    sleep 2
done
