#!/bin/sh -e

##########################################################################
#   Script description:
#       Download and cache a reference for samtools
#       
#   History:
#   Date        Name        Modification
#   2020-06-05              Begin
##########################################################################

usage()
{
    printf "Usage: $0 url\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
url="$1"
hash=$(echo $1 | cut -d / -f 7)
gpdir=$(echo $hash | cut -c 1-2)
pdir=$(echo $hash | cut -c 3-4)
fname=$(echo $hash | cut -c 5-)
dir="$HOME/.cache/hts-ref/$gpdir/$pdir"

printf "$url ==> $dir/$fname\n"
mkdir -p "$dir"
curl --continue-at - -o "$dir/$fname" "$url"
