#!/bin/sh -e

##########################################################################
#   Script description:
#       Fetch files in an SRA cart file using fusera
#       https://www.ncbi.nlm.nih.gov/sra/docs/dbgap-cloud-access/#mount-the-cloud-storage-data
#
#   Arguments:
#       Name of cart file
#       
#   History:
#   Date        Name        Modification
#   2019-10-11  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

# Mount opts for AWS only
if [ $(whoami) = ec2-user ]; then
    mount_opts="-l s3.us-east-1"
fi

mkdir -p $HOME/SRA-download/mount
for cart in *.krt; do
    all_srrs=$(prefetch -l $cart | cut -d '|' -f 3 | grep SRR)
    for srr in $all_srrs; do
	printf "===\nMounting cart $cart, srr $srr...\n"
	fusera mount $mount_opts -t prj_13558_D25493.ngc -a $srr \
	    $HOME/SRA-download/mount &
	sleep 2
	while [ 0$(ls mount) = 0 ]; do
	    printf "Waiting for fusera mount...\n"
	    sleep 2
	done
	ls -l mount/*
	ls -l mount/*/*.cram >> cram-sizes.txt
	time cat mount/*/*.cram > /dev/null
	time cat mount/*/*.cram > /dev/null
	
	# Needs to create reference cache .cache/hts-ref, which takes too long
	# time samtools view mount/*/*.cram > /dev/null
	# read -p "Press return when done with $srr..." junk
	fusera unmount $HOME/SRA-download/mount
	while [ 0$(ls mount) != 0 ]; do
	    printf "Waiting for fusera mount...\n"
	    sleep 2
	done
    done
done
