#!/bin/sh -e

##########################################################################
#   Script description:
#       Send multiple sample lists to cloud in parallel
#       
#   History:
#   Date        Name        Modification
#   2020-07-28  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 instance sample-file [sample-file ...]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 2 ]; then
    usage
fi

instance=$1
shift
for file in $@; do
    echo $file
    ./samples-to-cloud $file $instance
done
