#!/bin/sh -e

##########################################################################
#   Script description:
#       Run multiple ad2vcf.sh jobs together
#       
#   History:
#   Date        Name        Modification
#   2020-07-28              Begin
##########################################################################

usage()
{
    printf "Usage: $0 sample-file job-count\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi
sample_file=$1
job_count=$2
vcf_dir=VCFs-$(basename $sample_file)

prefix=$(basename $sample_file)-
split -d -n l/$job_count $sample_file $prefix
for file in ${prefix}-??; do
    echo $file
    nohup ./ad2vcf.sh $file $vcf_dir > $file.out 2> $file.err &
done
