#!/bin/sh -e

##########################################################################
#   Script description:
#       Upload samples to GCP instance or bucket
#       
#   History:
#   Date        Name        Modification
#   2020-07-27  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 sampe-file GCP-instance-name\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

sample_file=$1
instance=$2

gcloud compute scp $sample_file ${instance}:SRA
for sample in $(cat $sample_file); do
    gcloud compute scp Split-vcfs/Combined/combined.$sample.vcf.xz ${instance}:SRA
done
