#!/bin/sh -e

##########################################################################
#   Script description:
#       Upload samples to GCP instance or bucket
#       
#   History:
#   Date        Name        Modification
#   2020-07-27  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 sample-file GCP-instance-name\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

sample_file=$1
instance=$2

sample_base=VCFs-$(basename $sample_file)
dest_dir=Haplohseq-analysis/SRA
gcloud compute ssh $instance --command="mkdir -p $dest_dir"
mkdir -p $sample_base
for sample in $(cat $sample_file); do
    ln -f ../Split-vcfs/Combined/combined.$sample.vcf.xz $sample_base
done
gcloud compute scp --recurse $sample_base ${instance}:$dest_dir
rm -rf $sample_base
