#!/bin/sh -e

##########################################################################
#   Script description:
#       Upload samples to GCP instance or bucket
#       
#   History:
#   Date        Name        Modification
#   2020-07-27  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 sample-file GCP-instance-name\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

sample_file=$1
instance=$2

sample_dir=VCFs-$(basename $sample_file)
dest_dir=Haplohseq-analysis/SRA
gcloud compute ssh $instance --command="mkdir -p $dest_dir"
rm -rf $sample_dir
mkdir -p $sample_dir
for sample in $(cat $sample_file); do
    if ! ln ../Split-vcfs/Combined/combined.$sample.vcf.xz $sample_dir; then
	printf "$sample\n" >> missing-samples.txt
    fi
done
find $sample_dir -type f | wc -l
gcloud compute scp --recurse $sample_dir ${instance}:$dest_dir
rm -rf $sample_dir
