#!/bin/sh

##########################################################################
#   Script description:
#       Visually inspect ad2vcf outputs
#       
#   History:
#   Date        Name        Modification
#   2020-09-09  EC2 Default UserBegin
##########################################################################

usage()
{
    printf "Usage: $0 VCF-dir\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
vcf_dir=$1

ls $vcf_dir/*[0-9].vcf.xz | wc -l
ls $vcf_dir/Done/*.vcf.xz | wc -l
ls $vcf_dir/*[0-9].vcf.xz | cut -d . -f 2 > undone
ls $vcf_dir/Done/*.vcf.xz | cut -d . -f 2 | cut -d - -f 1 > done
diff undone done
