#!/bin/sh -e

##########################################################################
#   Script description:
#       Restart currently running jobs
#       
#   History:
#   Date        Name        Modification
#   2020-07-29              Begin
##########################################################################

usage()
{
    printf "Usage: $0 sample-file\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
path=$1

sample_file=$(basename $1)
if ! echo $sample_file | grep -q -e '-[0-9][0-9]'; then
    printf "Sample file should end in - followed by 2 digits.\n"
    exit 1
fi

cd /home/ec2-user/Haplohseq-analysis/SRA
AWS-scripts/stop-jobs $path
git pull
AWS-scripts/parallel-ad2vcf $path
