#!/bin/sh -e

##########################################################################
#   Script description:
#       Stop currently running jobs
#       
#   History:
#   Date        Name        Modification
#   2020-07-29              Begin
##########################################################################

usage()
{
    printf "Usage: $0 sample-file MAPQ-min\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi
sample_file=$(basename $1)
mapq_min=$2

if ! echo $sample_file | grep -q -e '-[0-9][0-9]'; then
    printf "Sample file should end in - followed by 2 digits.\n"
    exit 1
fi

vcf_dir=VCFs-$sample_file
suffix=${sample_file##*-}

log_dir=$vcf_dir/Logs-MAPQ-$mapq_min
if [ ! -d $log_dir ]; then
    printf "$log_dir does not exist or is not a directory.\n"
    exit 1
fi

read -p 'Are you sure? yes/[no] ' sure
if [ 0$sure != 0yes ]; then
    exit
fi

cd /home/ec2-user/Haplohseq-analysis/SRA
pkill samtools || true
pkill ad2vcf || true
top
./AWS-scripts/unmount-all

rm -f $vcf_dir/*-ad* || true
rm -f $sample_file-?? || true

c=1
while [ -e $log_dir.$c ]; do
    c=$((c + 1))
done
mv $log_dir $log_dir.$c
