#!/bin/sh -e

##########################################################################
#   Script description:
#       Merge AD-enhanced VCFs from AWS group into a single directory
#       
#   History:
#   Date        Name        Modification
#   2020-09-13  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 sample-group MAPQ-min\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi
sample_group=$1
mapq_min=$2

combined_dir=AD-VCFs-$sample_group-MAPQ-$mapq_min
mkdir -p $combined_dir
printf "Linking to $combined_dir...\n"
find SRA/VCFs-$sample_group-samples-[0-9]*/Done-MAPQ-$mapq_min -name '*.vcf.xz' \
    -exec ln -f '{}' $combined_dir \;

master_list=$combined_dir/vcfs.txt
printf "Building $master_list...\n"
find $combined_dir -name '*-ad.vcf.xz' > $master_list

printf "Splitting list into 6 chunks for SLURM jobs...\n"
chunks=6
total_lines=$(cat $master_list | wc -l)
lines=$(($total_lines / $chunks + 1))
split -d -l $lines $master_list ${master_list%.*}-
