#!/bin/sh -e

cd ~/Data/TOPMed/Jobs/Haplohseq-analysis
temp_array=array-temp.txt
awk -F , '$1 !~ "sampleID" { printf("%s - WHI\n", $10); }' Misc/WHI_LOH_events_array.csv \
    | tr -d '"' > $temp_array

run_table=temp-runtable.txt
xzcat SRA/TOPMed_SraRunTable_20200920.txt.xz > $run_table
while read line; do
    nwd=$(echo $line | awk '{ print $1 }')
    # Brutally inefficient, but it adds up to about a minute so who cares...
    srr=$(awk '$3 == "'$nwd'" { print $4 }' $run_table)
    printf "%s %s WHI\n" $nwd $srr
done < $temp_array > SRA/Samples/array-samples.txt
rm -f $run_table $temp_array
