#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2019-10-11  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 hash request-#\n"
    printf "Get the hash from dbGaP download website.\n\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

hash="$1"
request=$2
set -x
aspera_prefix=$HOME/.aspera/cli
$aspera_prefix/bin/ascp -QTr -l 300M -k 1 \
    -i $aspera_prefix/etc/asperaweb_id_dsa.openssh \
    -W $hash \
    dbtest@gap-upload.ncbi.nlm.nih.gov:data/instant/jtocino/$request .
