#!/bin/sh -e

##########################################################################
#   Script description:
#       Deidentify event files and link into Events dir
#       
#   History:
#   Date        Name        Modification
#   2020-08-24  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 haplohseq-dir\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $(hostname -s) != barracuda ]; then
    printf "$0 must be run on barracuda.\n"
    exit 1
fi
if [ $# != 1 ]; then
    usage
fi
dir=$1

events_dir=$(echo $dir | sed -e 's|/|-|g')
mkdir -p $events_dir
sn=1
unconverted=0
converted=0
map_file=$dir/ID-map.txt
rm -f $map_file
for event_file in $(find $dir -maxdepth 1 -name 'combined.NWD*.events.dat'); do
    base=$(basename $event_file)
    # hash=$(printf "%04s" $sn)
    nwid=$(echo $base | cut -d . -f 2)
    # hash=$(sed -e 's|"||g' ../Misc/WHI_LOH_events_array.csv \
    #     | awk -F , -v nwid=$nwid '$10 == nwid { print $1 }' | uniq)
    hash=$(awk -F '[,.]' -v nwid=$nwid '$1 == nwid { print $2 }' \
	Misc/whi-filenames.csv | uniq)
    if [ 0$hash = 0 ]; then
	printf "No conversion found for $nwid.\n"
	unconverted=$((unconverted+1))
    else
	printf "%s %s\n" $nwid $hash >> $map_file
	
	deident=$(basename $event_file | sed -E "s|NWD[0-9]+|$hash|")
	printf "$event_file -> $deident\n"
	ln -f $event_file $events_dir/$deident

	param_file=$(echo $event_file | sed -e 's|\.events\.|.param.|')
	deident=$(basename $param_file | sed -E "s|NWD[0-9]+|$hash|")
	printf "$param_file -> $deident\n"
	ln -f $param_file $events_dir/$deident

	posterior_file=$(echo $event_file | sed -e 's|\.events\.|.posterior.|')
	deident=$(basename $posterior_file | sed -E "s|NWD[0-9]+|$hash|")
	printf "$posterior_file -> $deident\n"
	ln -f $posterior_file $events_dir/$deident
	
	converted=$((converted+1))
    fi
    sn=$((sn + 1))
done
printf "Unconverted: $unconverted  Converted: $converted\n"

# Full archive with posterior files
# Use low compression level or it will take hours for even 855 samples

tar -Jcvf ~/www/Temp/$events_dir.txz --options xz:compression-level=1 $events_dir

# Much smaller archive without posterior files
rm -f $events_dir/*.posterior.dat
tar -Jcvf ~/www/Temp/$events_dir-no-posterior.txz $events_dir

rm -rf $events_dir
chmod 644 ~/www/Temp/*
ls -l ~/www/Temp
