#!/bin/sh -e

##########################################################################
#   Script description:
#       Deidentify event files and link into Events dir
#       
#   History:
#   Date        Name        Modification
#   2020-08-24  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 haplohseq-output-dir\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
dir=$1

events_dir=${dir%/Haplo-output*}
events_dir=$(echo $events_dir | sed -e 's|/|-|g')
mkdir -p $events_dir
sn=1
unconverted=0
converted=0
map_file=$dir/ID-map.txt
rm -f $map_file
for file in $(find $dir -maxdepth 1 -name 'combined.NWD*.events.dat'); do
    base=$(basename $file)
    # hash=$(printf "%04s" $sn)
    nwid=$(echo $base | cut -d . -f 2)
    # hash=$(sed -e 's|"||g' ../Misc/WHI_LOH_events_array.csv \
    #     | awk -F , -v nwid=$nwid '$10 == nwid { print $1 }' | uniq)
    hash=$(awk -F '[,.]' -v nwid=$nwid '$1 == nwid { print $2 }' \
	Misc/whi-filenames.csv | uniq)
    if [ 0$hash = 0 ]; then
	# printf "No conversion found for $nwid.\n"
	unconverted=$((unconverted+1))
    else
	printf "%s %s\n" $nwid $hash >> $map_file
	deident=$(basename $file | sed -E "s|NWD[0-9]+|$hash|")
	printf "$file -> $deident\n"
	converted=$((converted+1))
	ln -f $file $events_dir/$deident
    fi
    sn=$((sn + 1))
done
printf "Unconverted: $unconverted  Converted: $converted\n"
tar Jcvf ~/www/Temp/$events_dir.txz $events_dir
chmod 644 ~/www/Temp/$events_dir.txz
ls -l ~/www/Temp
