#!/bin/sh

zhoudir=~zhou63/Filtered-VCFs/
mkdir -p $zhoudir
printf "Removing old files...\n"
find $zhoudir -type f -exec rm -f '{}' \;
for group in whi bjm group3 group4; do
    for batch in $(seq -f '%02g' 0 9); do
	dir=Data/AD-VCFs-$group-MAPQ-0/MAF-0.01-1000nt-sv
	printf "Linking $dir...\n"
	find $dir -maxdepth 1 -name 'combined*.vcf.xz' -print -exec ln -f '{}' $zhoudir \;
    done
done
find ~zhou63/Filtered-VCFs/ -type d -exec chown zhou63:zhou63 '{}' \;
find ~zhou63/Filtered-VCFs/ -type f -exec chmod 644 '{}' +
